name       : man-db
version    : 2.11.2
release    : 27
source     :
    - https://download.savannah.nongnu.org/releases/man-db/man-db-2.11.2.tar.xz : cffa1ee4e974be78646c46508e6dd2f37e7c589aaab2938cc1064f058fef9f8d
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
