name       : man-db
version    : 2.8.7
release    : 22
source     :
    - https://getsol.us/sources/man-db-2.8.7.tar.xz : b9cd5bb996305d08bfe9e1114edc30b4c97be807093b88af8033ed1cf9beb326
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
