name       : man-db
version    : 2.8.6.1
release    : 18
source     :
    - https://download.savannah.gnu.org/releases/man-db/man-db-2.8.6.1.tar.xz : 2c77a2bb9dbf06f72417a6f63063e204888a22a5020ff77334d304d55f813a28
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
