name        : man-db
version     : 2.7.5
release     : 8
source      :
    - http://download.savannah.gnu.org/releases/man-db/man-db-2.7.5.tar.xz : 5c4ddd0d67abbbcb408dc5804906f62210f7c863ef791198faca3d75681cca14
license     :
    - GPL-2.0+
    - LGPL-2.1
summary     : Application to read Linux man pages
builddeps   :
    - pkgconfig(libpipeline)
    - pkgconfig(zlib)
    - gdbm-devel
rundeps     :
    - groff
component   : system.utils
description : |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch
    %patch -p1 < $pkgfiles/0001-Don-t-use-nonexistent-user.patch
    autoreconf -vfi
    %configure --disable-setuid --disable-static
build      : |
    %make
install    : |
    %make_install
