name       : man-db
version    : 2.9.1
release    : 23
source     :
    - https://savannah.nongnu.org/download/man-db/man-db-2.9.1.tar.xz : ba3d8afc5c09a7265a8dabfa0e7c1f4b3ab97df9abf1f6810faa8f301056c74f
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
