name       : man-db
version    : 2.11.0
release    : 26
source     :
    - https://mirror.hostiran.ir/gnu/releases/man-db/man-db-2.11.0.tar.xz : 4130e1a6241280359ef5e25daec685533c0a1930674916202ab0579e5a232c51
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
