name       : man-db
version    : 2.8.4
release    : 15
source     :
    - https://download.savannah.gnu.org/releases/man-db/man-db-2.8.4.tar.xz : 103c185f9d8269b9ee3b8a4cb27912b3aa393e952731ef96fedc880723472bc3
license    : GPL-3.0-or-later
component  : system.utils
summary    : Application to read Linux man pages
description: |
    man-db is an implementation of the standard Unix documentation system accessed using the man command. It uses a Berkeley DB database in place of the traditional flat-text whatis databases.
builddeps  :
    - pkgconfig(libpipeline)
    - pkgconfig(zlib)
    - gdbm-devel
    - groff
rundeps    :
    - groff
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch

    %reconfigure --disable-static \
        --disable-setuid \
        --enable-cache-owner=root
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
